### ISSUE TITLE
Industrial Park doesn't open on Windows 10

### ISSUE THREAD

**Issue by ScaryPancake** [igorseabra4/IndustrialPark#1]
Opening the executable attempts to load, only for it to be "suspended" then it closes. I haven't had any luck trying to open it (yet), even with troubleshooting.

Some Computer Specs:
Windows 10 Home 64-bit
AMD FX(tm)-4130 Quad-Core Processor
NVIDIA GeForce GTX 650
RAM 16 GB

**Comment by Eurose209** [comment]
Reproduced this on my own Windows 10 PC.

**Comment by ScaryPancake** [comment]
@Eurose209 This didn't work. I already have the three OBJ files in the Resources/Models folder. I did replace them with the ones in your zip file, but nothing happened.

**Comment by Eurose209** [comment]
You also need to build HipHopFile and RenderWareFile, which are in separate repos under igorseabra4's profile. HipHopFile is a project in the HipHopTool solution:

[RenderWareFile repo](https://github.com/igorseabra4/RenderWareFile)
[HipHopTool repo](https://github.com/igorseabra4/HipHopTool)

Once you build both of these, you will get a .DLL file for each one. You need to add a reference to the IndustrialPark project in Visual Studio for both of these.
