### ISSUE TITLE
Not compatible with Python.

### ISSUE THREAD

**Issue by TheProtaganist** [igorseabra4/IndustrialPark#24]
Hi I see this project is written in C sharp which is a language I am not familiar with. Is there a python equivalent to this project?

**Comment by ItsPepperpot** [comment]
Closing this issue as it is old. To answer the question: There's no Python HIP/HOP editor similar to Industrial Park that I'm aware of; Watto GameExtractor and QuickBMS are both capable of extracting data from archives, but they are programmed in Java and C respectively.
