### ISSUE TITLE
NoData error displayed when opening native HIPs containing empty ANIM assets

### ISSUE THREAD

**Issue by ItsPepperpot** [igorseabra4/IndustrialPark#67]
NoData error generated when opening a level containing empty ANIM assets (e.g. BB02.hop)

**Comment by energydrink02** [comment]
NoData means the asset is of 0 bytes length. Those are usually empty animation assets which incorrectly have ".ATBL" in their name.
https://github.com/igorseabra4/IndustrialPark/blob/e4f184c1209a8006a3b30c57f5420bd085a1b76d/IndustrialPark/ArchiveEditor/ArchiveEditorFunctions.cs#L749-L753)
